name: ${pluginName}
version: ${pluginVersion}
description: ${pluginDescription}
author: ${pluginAuthor}
website: ${pluginWebsite}

main: com.worldprotect.WorldProtectPlugin
api-version: '1.17'

depend: []
softdepend: [ 'Vault', 'WorldEdit', 'PlaceholderAPI' ]

commands:
  wp:
    description: Main World Protect command
    usage: /<command> <subcommand> [args]
    aliases: [ worldprotect, protect ]
    permission: worldprotect.use

permissions:
  worldprotect.admin:
    description: Full administrative access to all World Protect features
    default: op
    children:
      worldprotect.use: true
      worldprotect.command.*: true
  
  worldprotect.use:
    description: Basic permission to use World Protect commands
    default: true
    children:
      worldprotect.command.help: true
      worldprotect.command.version: true
      worldprotect.command.info: true
      worldprotect.command.list: true
      worldprotect.command.flags: true
      worldprotect.command.wand: true
  
  worldprotect.command.*:
    description: Wildcard for all World Protect command permissions
    default: op
  
  worldprotect.command.help:
    description: Access to help command
    default: true
  
  worldprotect.command.create:
    description: Create areas
    default: op
  
  worldprotect.command.delete:
    description: Delete areas
    default: op
  
  worldprotect.command.list:
    description: List all areas
    default: true
  
  worldprotect.command.info:
    description: View area information
    default: true
  
  worldprotect.command.flags:
    description: List available flags
    default: true
  
  worldprotect.command.flag:
    description: Set area flags
    default: op
  
  worldprotect.command.wand:
    description: Get selection wand
    default: op
  
  worldprotect.command.reload:
    description: Reload plugin configuration
    default: op
  
  worldprotect.command.version:
    description: View plugin version
    default: true
  
  worldprotect.wand:
    description: Use selection wand
    default: op
  
  worldprotect.bypass:
    description: Bypass all area protections
    default: op

# Plugin libraries
libraries:
  - dev.dejvokep:boosted-yaml:1.3.4

# Folia support
folia-supported: true

# Plugin metrics (bStats)
metrics:
  enabled: true
  plugin-id: 00000  # TODO: Set actual bStats ID

# Update checker
updater:
  enabled: true
  channel: release